---
title: "P8106_group2recovery_primaryanalysis" 
author: "Yimin Chen (yc4195), Yang Yi (yy3307), Qingyue Zhuo (qz2493)"
output:
  pdf_document:
    toc: yes
    toc_depth: 2
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(caret)
library(corrplot)
library(ggplot2)
library(AppliedPredictiveModeling)
library(klaR)
library(MASS)
library(pROC)
library(rpart.plot)
library(randomForest)
library(ranger)
library(glmnet)
library(earth)
```

# Import and data manipulation

```{r, results='hide'}
# Load recovery.RData environment
load("./recovery.Rdata")

dat %>% na.omit()

# dat1 draw a random sample of 2000 participants Uni:3307
set.seed(3307)

dat1 = dat[sample(1:10000, 2000),]

dat1 = 
  dat1[, -1] %>% 
  mutate(
    gender = as.factor(gender),
    race = as.factor(race),
    smoking = as.factor(smoking),
    hypertension = as.factor(hypertension),
    diabetes = as.factor(diabetes),
    vaccine = as.factor(vaccine),
    severity = as.factor(severity),
    study = as.factor(
      case_when(study == "A" ~ 1, study == "B" ~ 2, study == "C" ~ 3)
      )
    )

# dat2 draw a random sample of 2000 participants Uni:2493
set.seed(2493)

dat2 = dat[sample(1:10000, 2000),]

dat2 = 
  dat2[, -1] %>% 
  mutate(
    gender = as.factor(gender),
    race = as.factor(race),
    smoking = as.factor(smoking),
    hypertension = as.factor(hypertension),
    diabetes = as.factor(diabetes),
    vaccine = as.factor(vaccine),
    severity = as.factor(severity),
    study = as.factor(
      case_when(study == "A" ~ 1, study == "B" ~ 2, study == "C" ~ 3)
      )
    )

# Merged dataset with unique observation
covid_dat = rbind(dat1, dat2) %>% 
  unique()

covid_dat2 = model.matrix(recovery_time ~ ., covid_dat)[, -1]

# Partition dataset into two parts: training data (70%) and test data (30%)
rowTrain = createDataPartition(y = covid_dat$recovery_time, p = 0.7, list = FALSE)

trainData = covid_dat[rowTrain, ]
testData = covid_dat[-rowTrain, ]

ctrl1 = trainControl(method = "repeatedcv", number = 10, repeats = 5)
```

# Data visualization

## Correlation plot

```{r}
corr_dat = covid_dat[rowTrain,] %>% 
  dplyr::select('age', 'height', 'weight', 'bmi', 'SBP', 'LDL')
corrplot(cor(corr_dat), method = "circle", type = "full")
```

## Feature plot

```{r}
vis_trdat = trainData %>% 
  dplyr::select('age', 'height', 'weight', 'bmi', 'SBP', 'LDL', 'recovery_time')

theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .5)
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1)
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)

featurePlot(x = vis_trdat[, 1:6],
            y = vis_trdat[, 7],
            plot = "scatter",
            span = 0.5,
            labels = c("Predictors", "Recovery Time"),
            type = c("p", "smooth"))
```

## Boxplot

```{r,echo=FALSE}
# Merge all boxplots
par(mfrow = c(2, 4))
par(cex.lab=1.5, cex.axis=1.3, cex.main=1.8)
options(scipen=999)
# 
boxplot(recovery_time ~ gender, data = trainData, xlab = "Gender", ylim = c(0, 150), 
         col = "#3366CC", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ race, data = trainData, xlab = "Race", ylim = c(0, 150), 
       col = "#DC3912", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ smoking, data = trainData, xlab = "Smoking", ylim = c(0, 150), 
        col = "#FF9900", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ hypertension, data = trainData, xlab = "Hypertension", ylim = c(0, 150), 
        col = "#109618", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ diabetes, data = trainData, xlab = "Diabetes", ylim = c(0, 150), 
         col = "#990099", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ vaccine, data = trainData, xlab = "Vaccine", ylim = c(0, 150), 
        col = "#0099C6", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ severity, data = trainData, xlab = "Severity", ylim = c(0, 150), 
        col = "#DD4477", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

boxplot(recovery_time ~ study, data = trainData, xlab = "Study", ylim = c(0, 150), 
         col = "#66AA00", boxwex = 0.5, medcol = "white", 
        whiskcol = "gray", staplecol = "gray", outcol = "gray", font.main = 1)

```

```{r}
bp_gender = boxplot(recovery_time ~ gender, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_race = boxplot(recovery_time ~ race, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_smoking = boxplot(recovery_time ~ smoking, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_hypertension = boxplot(recovery_time ~ hypertension, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_diabetes = boxplot(recovery_time ~ diabetes, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_vaccine = boxplot(recovery_time ~ vaccine, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_severity = boxplot(recovery_time ~ severity, data = trainData, xlab = "Study", ylim = c(0, 150))
```

```{r}
bp_study = boxplot(recovery_time ~ study, data = trainData, xlab = "Study", ylim = c(0, 150))
```

# Model training

## GAM
```{r}
set.seed(2)
gam.fit = train(x = covid_dat2[rowTrain,],
                y = covid_dat$recovery_time[rowTrain],
                method = "gam",
                tuneGrid = data.frame(method = "GCV.Cp", select = c(TRUE,FALSE)),
                trControl = ctrl1)

gam.fit$bestTune
gam.fit$finalModel

# test error
pred.gam = predict(gam.fit, newdata = covid_dat2[-rowTrain,])
gam.RMSE = mean((pred.gam - covid_dat$recovery_time[-rowTrain])^2)
gam.RMSE
```

## MARS
```{r}
mars_grid = expand.grid(degree = 1:3,
                        nprune = 2:15)

set.seed(2)
mars.fit = train(x = covid_dat2[rowTrain,],
                 y = covid_dat$recovery_time[rowTrain],
                 method = "earth",
                 tuneGrid = mars_grid,
                 trControl = ctrl1)

ggplot(mars.fit)
mars.fit$bestTune
mars.fit$finalModel

# test error
pred.mars = predict(mars.fit, newdata = covid_dat2[-rowTrain,])
mars.RMSE = mean((pred.mars - covid_dat$recovery_time[-rowTrain])^2)
mars.RMSE
```


## Regression tree
```{r}
set.seed(2)

#Build a regression tree on the training data to predict the respons
rpart.fit = train(recovery_time ~ . ,
                  covid_dat[rowTrain,],
                  method = "rpart",
                  tuneGrid = data.frame(cp = exp(seq(-6,-2, length = 50))),
                  trControl =ctrl1,
                  preProcess = c("center", "scale"))

rpart.fit$bestTune


#plot of the tree
ggplot(rpart.fit, highlight = TRUE)

rpart.plot(rpart.fit$finalModel)

# Report the variable importance
summary(rpart.fit$finalModel, las = 2, cBars = 19, cex.names = 0.6)
plot(varImp(rpart.fit, scale = TRUE))

## rpart does not have RMSE
```

## Random Forest
```{r}
ctrlrf = trainControl(method = "cv")

# Using Caret package to build random forest plot
rf.grid = expand.grid(mtry = 1:16,
                      splitrule = "variance",
                      min.node.size = 1:6)

set.seed(2)
rf.fit = train(recovery_time ~ .,
               covid_dat[rowTrain,],
               method = "ranger",
               tuneGrid = rf.grid,
               trControl = ctrlrf)

ggplot(rf.fit, highlight = TRUE)

# Best tunning parameter
rf.fit$bestTune

# Variable importance
rf2.final.per = ranger(recovery_time ~ .,
                covid_dat[rowTrain,],
                mtry = rf.fit$bestTune[[1]],
                splitrule = "variance",
                min.node.size = rf.fit$bestTune[[3]],
                importance = "permutation",
                scale.permutation.importance = TRUE)

barplot(sort(ranger::importance(rf2.final.per), decreasing = FALSE),
        las = 2, horiz = TRUE, cex.names = 0.7,
        col = colorRampPalette(colors = c("cyan","blue"))(16))

# test error

set.seed(2)
rffit_pred = predict(rf.fit, newdata = covid_dat[-rowTrain,])
rffit.RMSE = RMSE(rffit_pred, covid_dat$recovery_time[-rowTrain])
rffit.RMSE
```

## Boosting
```{r}
ctrlboost = trainControl(method = "cv")

gbm_grid = expand.grid(n.trees = c(100, 250, 500, 1000, 2000, 3000),
                       interaction.depth = 1:3,
                       shrinkage = c(0.0005,0.001,0.002),
                       n.minobsinnode = 1)
set.seed(2)
gbm.fit = train(recovery_time ~ . ,
               covid_dat[rowTrain,],
               tuneGrid = gbm_grid,
               trControl = ctrlboost,
               method = "gbm",
               verbose = FALSE)

gbm.fit$bestTune
ggplot(gbm.fit, highlight = TRUE)
# Report the variable importance
summary(gbm.fit$finalModel, las = 2, cBars = 19, cex.names = 0.6)
#test error
set.seed(2)
pred.gbm = predict(gbm.fit, newdata = covid_dat[-rowTrain,])
gbm.RMSE = RMSE(pred.gbm, covid_dat$recovery_time[-rowTrain])
gbm.RMSE
```

# Model selection

